# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=250, verbose_name='Virtual Machine name')),
                ('location', models.CharField(choices=[('westus', 'West US'), ('westus2', 'West US2'), ('centralus', 'Central US'), ('eastasia', 'East Asia'), ('southeastasia', 'South East Asia'), ('eastus', 'East US'), ('eastus2', 'East US2'), ('northcentralus', 'North Central US'), ('southcentralus', 'South Central US'), ('westcentralus', 'West Central US'), ('northeurope', 'North Europoe'), ('westeurope', 'West Europe'), ('japaneast', 'Japan EAST'), ('japanwest', 'Japan WEST'), ('brazilsouth', 'Brazil South'), ('australiasoutheast', 'Australia South East'), ('australiaeast', 'Australia EAST'), ('westindia', 'West India'), ('southindia', 'South India'), ('centralindia', 'Central India'), ('canadacentral', 'Canada Central'), ('canadaeast', 'Canada East'), ('uksouth', 'UK South'), ('ukwest', 'UK West'), ('koreacentral', 'Korea Central'), ('koreasouth', 'Korea South')], default='10.0.0.0/16', max_length=250, verbose_name='Location')),
                ('vm_reference', models.CharField(choices=[('linux', 'linux'), ('windows', 'windows')], default='linux', max_length=250, verbose_name='Operating System')),
            ],
        ),
        migrations.AlterField(
            model_name='nic',
            name='location',
            field=models.CharField(choices=[('westus', 'West US'), ('westus2', 'West US2'), ('centralus', 'Central US'), ('eastasia', 'East Asia'), ('southeastasia', 'South East Asia'), ('eastus', 'East US'), ('eastus2', 'East US2'), ('northcentralus', 'North Central US'), ('southcentralus', 'South Central US'), ('westcentralus', 'West Central US'), ('northeurope', 'North Europoe'), ('westeurope', 'West Europe'), ('japaneast', 'Japan EAST'), ('japanwest', 'Japan WEST'), ('brazilsouth', 'Brazil South'), ('australiasoutheast', 'Australia South East'), ('australiaeast', 'Australia EAST'), ('westindia', 'West India'), ('southindia', 'South India'), ('centralindia', 'Central India'), ('canadacentral', 'Canada Central'), ('canadaeast', 'Canada East'), ('uksouth', 'UK South'), ('ukwest', 'UK West'), ('koreacentral', 'Korea Central'), ('koreasouth', 'Korea South')], default='westus', max_length=250),
        ),
        migrations.AlterField(
            model_name='ressources',
            name='groupe_name',
            field=models.CharField(max_length=250, verbose_name='Groupe name'),
        ),
        migrations.AlterField(
            model_name='ressources',
            name='location',
            field=models.CharField(choices=[('westus', 'West US'), ('westus2', 'West US2'), ('centralus', 'Central US'), ('eastasia', 'East Asia'), ('southeastasia', 'South East Asia'), ('eastus', 'East US'), ('eastus2', 'East US2'), ('northcentralus', 'North Central US'), ('southcentralus', 'South Central US'), ('westcentralus', 'West Central US'), ('northeurope', 'North Europoe'), ('westeurope', 'West Europe'), ('japaneast', 'Japan EAST'), ('japanwest', 'Japan WEST'), ('brazilsouth', 'Brazil South'), ('australiasoutheast', 'Australia South East'), ('australiaeast', 'Australia EAST'), ('westindia', 'West India'), ('southindia', 'South India'), ('centralindia', 'Central India'), ('canadacentral', 'Canada Central'), ('canadaeast', 'Canada East'), ('uksouth', 'UK South'), ('ukwest', 'UK West'), ('koreacentral', 'Korea Central'), ('koreasouth', 'Korea South')], default='westus', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='storage_account_name',
            field=models.CharField(max_length=250, verbose_name='Storage account name'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='address_prefixes',
            field=models.CharField(choices=[('10.0.0.0/10', '10.0.0.0/10'), ('10.0.0.0/11', '10.0.0.0/11'), ('10.0.0.0/12', '10.0.0.0/12'), ('10.0.0.0/13', '10.0.0.0/13'), ('10.0.0.0/14', '10.0.0.0/14'), ('10.0.0.0/15', '10.0.0.0/15'), ('10.0.0.0/16', '10.0.0.0/16'), ('192.168.1.0/16', '192.168.1.0/16'), ('192.168.1.0/17', '192.168.1.0/17'), ('192.168.1.0/18', '192.168.1.0/18'), ('192.168.1.0/19', '192.168.1.0/19'), ('192.168.1.0/20', '192.168.1.0/20'), ('172.16.1.0/10', '172.16.1.0/10'), ('172.16.1.0/11', '172.16.1.0/11'), ('172.16.1.0/12', '172.16.1.0/12'), ('172.16.1.0/13', '172.16.1.0/13'), ('172.16.1.0/14', '172.16.1.0/14'), ('172.16.1.0/15', '172.16.1.0/15'), ('172.16.1.0/16', '172.16.1.0/16')], default='10.0.0.0/16', max_length=250),
        ),
        migrations.AlterField(
            model_name='vnet',
            name='address_prefixes',
            field=models.CharField(choices=[('10.0.0.0/10', '10.0.0.0/10'), ('10.0.0.0/11', '10.0.0.0/11'), ('10.0.0.0/12', '10.0.0.0/12'), ('10.0.0.0/13', '10.0.0.0/13'), ('10.0.0.0/14', '10.0.0.0/14'), ('10.0.0.0/15', '10.0.0.0/15'), ('10.0.0.0/16', '10.0.0.0/16'), ('192.168.1.0/16', '192.168.1.0/16'), ('192.168.1.0/17', '192.168.1.0/17'), ('192.168.1.0/18', '192.168.1.0/18'), ('192.168.1.0/19', '192.168.1.0/19'), ('192.168.1.0/20', '192.168.1.0/20'), ('172.16.1.0/10', '172.16.1.0/10'), ('172.16.1.0/11', '172.16.1.0/11'), ('172.16.1.0/12', '172.16.1.0/12'), ('172.16.1.0/13', '172.16.1.0/13'), ('172.16.1.0/14', '172.16.1.0/14'), ('172.16.1.0/15', '172.16.1.0/15'), ('172.16.1.0/16', '172.16.1.0/16')], default='10.0.0.0/16', max_length=250, verbose_name='Address prefixes'),
        ),
        migrations.AlterField(
            model_name='vnet',
            name='location',
            field=models.CharField(choices=[('westus', 'West US'), ('westus2', 'West US2'), ('centralus', 'Central US'), ('eastasia', 'East Asia'), ('southeastasia', 'South East Asia'), ('eastus', 'East US'), ('eastus2', 'East US2'), ('northcentralus', 'North Central US'), ('southcentralus', 'South Central US'), ('westcentralus', 'West Central US'), ('northeurope', 'North Europoe'), ('westeurope', 'West Europe'), ('japaneast', 'Japan EAST'), ('japanwest', 'Japan WEST'), ('brazilsouth', 'Brazil South'), ('australiasoutheast', 'Australia South East'), ('australiaeast', 'Australia EAST'), ('westindia', 'West India'), ('southindia', 'South India'), ('centralindia', 'Central India'), ('canadacentral', 'Canada Central'), ('canadaeast', 'Canada East'), ('uksouth', 'UK South'), ('ukwest', 'UK West'), ('koreacentral', 'Korea Central'), ('koreasouth', 'Korea South')], default='westus', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vnet',
            name='vnet_name',
            field=models.CharField(max_length=250, verbose_name='Virtual network name'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='nic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.Nic'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.Ressources'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.Storages'),
        ),
    ]
