# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0002_auto_20170430_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='os_disk_name',
            field=models.CharField(default='ss', max_length=250),
        ),
    ]
